### ISSUE TITLE
Encrypted reversing

### ISSUE THREAD

**Issue by dbeattie71** [towbes/daoc-logger#1]
Not reversing I guess but hooking send/rcv before and after encryption/decryption.

You might want to checkout
https://github.com/dbeattie71/ak

Old code from Autokiller.

**Comment by towbes** [comment]
Oh thank you for the link!!! I found the autokiller site on archive.org and it looked really interesting.

**Comment by towbes** [comment]
Wow this is really impressive.  Again thank you for sharing.  This will take a long time to digest.  Looks like you really did a good job of organizing the code too.  I still have a lot to learn in regards to those direct assembly hooks

**Comment by dbeattie71** [comment]
I'm not the original author.  The guy that wrote it quit playing and sent me the source.

**Comment by towbes** [comment]
Ah gotcha, very cool anyway.  I actually have the old dll / exe downloaded haha , dug through archive.org snapshots from the early 2000s

**Comment by dbeattie71** [comment]
I think all the projects eaily load up and port in latest VS, at least 2019 I believe.
